# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import google.protobuf.descriptor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='config.proto',
  package='',
  serialized_pb='\n\x0c\x63onfig.proto\x1a google/protobuf/descriptor.proto\"P\n\x10\x44\x65viceDescriptor\x12\x11\n\tvendor_id\x18\x01 \x01(\r\x12\x12\n\nproduct_id\x18\x02 \x01(\r\x12\x15\n\rserial_number\x18\x03 \x01(\x0c\"\xb9\x01\n\rConfiguration\x12\x16\n\x0ewhitelist_urls\x18\x01 \x03(\x0c\x12\x16\n\x0e\x62lacklist_urls\x18\x02 \x03(\x0c\x12\x39\n\rwire_protocol\x18\x03 \x02(\x0b\x32\".google.protobuf.FileDescriptorSet\x12(\n\rknown_devices\x18\x04 \x03(\x0b\x32\x11.DeviceDescriptor\x12\x13\n\x0bvalid_until\x18\x05 \x01(\x05')




_DEVICEDESCRIPTOR = _descriptor.Descriptor(
  name='DeviceDescriptor',
  full_name='DeviceDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vendor_id', full_name='DeviceDescriptor.vendor_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_id', full_name='DeviceDescriptor.product_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='DeviceDescriptor.serial_number', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=50,
  serialized_end=130,
)


_CONFIGURATION = _descriptor.Descriptor(
  name='Configuration',
  full_name='Configuration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whitelist_urls', full_name='Configuration.whitelist_urls', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='blacklist_urls', full_name='Configuration.blacklist_urls', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='wire_protocol', full_name='Configuration.wire_protocol', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='known_devices', full_name='Configuration.known_devices', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_until', full_name='Configuration.valid_until', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=133,
  serialized_end=318,
)

_CONFIGURATION.fields_by_name['wire_protocol'].message_type = google.protobuf.descriptor_pb2._FILEDESCRIPTORSET
_CONFIGURATION.fields_by_name['known_devices'].message_type = _DEVICEDESCRIPTOR
DESCRIPTOR.message_types_by_name['DeviceDescriptor'] = _DEVICEDESCRIPTOR
DESCRIPTOR.message_types_by_name['Configuration'] = _CONFIGURATION

class DeviceDescriptor(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DEVICEDESCRIPTOR

  # @@protoc_insertion_point(class_scope:DeviceDescriptor)

class Configuration(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONFIGURATION

  # @@protoc_insertion_point(class_scope:Configuration)


# @@protoc_insertion_point(module_scope)
